# This file shall contain routes used to build URLs that are defined within the
# application. Routes that are not served by this application should be stored
# in routing_3rd_party.yml. This includes routes that will eventually be served
# by this application but have not yet been migrated

status:
    path: /status
    defaults: { _controller: App\Controller\StatusController }

find_by_pid:
    path: /programmes/{pid}
    # !find_by_pid is a special value, that shall be converted into an proper
    # _controller value (i.e. a class name) by the FindByPidRouterSubscriber
    defaults: { _controller: '!find_by_pid' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

# Programme information pages
programme_article:
    path: /programmes/articles/{key}/{slug}
    defaults: { _controller: App\Controller\Articles\ShowController, slug: '' }
    requirements: { key: '[a-zA-Z0-9-]{1,40}' }

programme_article_listings:
    path: /programmes/{pid}/articles
    defaults: { _controller: App\Controller\Articles\IndexController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}'}

programme_credits:
    path: /programmes/{pid}/credits
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, _fragment: 'credits', permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_episodes:
    path: /programmes/{pid}/episodes
    defaults: { _controller: App\Controller\ProgrammeEpisodes\IndexController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_episodes_guide:
    path: /programmes/{pid}/episodes/guide
    defaults: { _controller: App\Controller\ProgrammeEpisodes\GuideController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_episodes_guide_partial:
    path: /programmes/{pid}/episodes/guide.2013inc
    defaults: { _controller: App\Controller\ProgrammeEpisodes\GuidePartialController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_episodes_player:
    path: /programmes/{pid}/episodes/player
    defaults: { _controller: App\Controller\ProgrammeEpisodes\PlayerController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_upcoming_broadcasts:
    path: /programmes/{pid}/broadcasts/upcoming/{debut}
    defaults: { _controller: App\Controller\ProgrammeEpisodes\UpcomingController, debut: null}
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', debut: 'debut' }

programme_player:
    path: /programmes/{pid}/player
    defaults: { _controller: App\Controller\AncillaryPages\PlayerController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_profile:
    path: /programmes/profiles/{key}/{slug}
    defaults: { _controller: App\Controller\Profiles\ShowController, slug: '' }
    requirements: { key: '[a-zA-Z0-9-]{1,40}' }

programme_profile_listings:
    path: /programmes/{pid}/profiles
    defaults: { _controller: App\Controller\Profiles\IndexController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}'}

programme_recommendations:
    path: /programmes/{pid}/recommendations{extension}
    defaults: { _controller: App\Controller\RecommendationsController, extension: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', extension: '$|\.2013inc' }

programme_recipes:
    path: /programmes/{pid}/recipes
    defaults: { _controller: App\Controller\Recipes\RecipesController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_recipes_amen:
    path: /programmes/{pid}/recipes.ameninc
    defaults: { _controller: App\Controller\Recipes\RecipesAmenController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_recipes_ds2013:
    path: /programmes/{pid}/recipes.2013inc
    defaults: { _controller: App\Controller\Recipes\RecipesDs2013Controller }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_segments:
    path: /programmes/{pid}/segments
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, _fragment: 'segments', permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_suggestions:
    path: /programmes/{pid}/suggestions
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, _fragment: 'related_programmes', permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_episode_downloads_rss:
    path: /programmes/{pid}/episodes/downloads.rss
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: podcast_download_rss, permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

# Podcast
programme_podcast_episodes_download:
    path: /programmes/{pid}/episodes/downloads
    defaults: { _controller: App\Controller\Podcast\PodcastController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_podcasts:
    path: /programmes/{pid}/podcasts
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: programme_podcast_episodes_download, permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

# Galleries
programme_galleries:
    path: /programmes/{pid}/galleries
    controller: App\Controller\Gallery\GalleriesController
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

# Gallery
programme_gallery:
    path: /programmes/{pid}/{imagePid}
    controller: App\Controller\FindByPid\GalleryController
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', imagePid: '[0-9b-df-hj-np-tv-z]{8,15}' }

#Clips
programme_clips:
    path: /programmes/{pid}/clips
    defaults: { _controller: App\Controller\Clips\ListController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

# SMP Playlist page
programme_smp_playlist:
    path: /programmes/{pid}/playlist.json
    defaults: { _controller: App\Controller\SmpPlaylist\SmpPlaylistController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

# Schedules
schedules_home:
    path: /schedules
    defaults: { _controller: App\Controller\Schedules\HomeController }

schedules_by_day:
    path: /schedules/{pid}/{date}
    defaults: { _controller: App\Controller\Schedules\ByDayController, date: null }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/\d{2}/\d{2}' }

schedules_by_week:
    path: /schedules/{pid}/{date}
    defaults: { _controller: App\Controller\Schedules\ByWeekController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/w([0-4][0-9]|[5][0-3])' }

schedules_by_month:
    path: /schedules/{pid}/{date}
    defaults: { _controller: App\Controller\Schedules\ByMonthController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/\d{2}' }

schedules_by_vanity:
    path: /schedules/{pid}/{vanity}
    defaults: { _controller: App\Controller\Schedules\VanityRedirectController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', vanity: 'yesterday|today|tomorrow|(?:this|next|last)_(?:week|month)' }

schedules_by_year:
    path: /schedules/{pid}/{year}
    defaults: { _controller: App\Controller\Schedules\ByYearController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', year: '\d{4}' }

# Redirect: /schedules/network/<network_url_key>   --->   /schedules/<default service pid in network>
schedules_by_network_url_key:
    path: /schedules/network/{networkUrlKey}
    defaults: { _controller: App\Controller\Schedules\ByNetworkUrlKeyController }
    requirements: { networkUrlKey: '[a-zA-Z0-9]{2,35}' }

schedules_on_now:
    path: /schedules/network/{networkUrlKey}/on-now
    defaults: { _controller: App\Controller\Schedules\Lazyload\OnNowController }
    requirements: { networkUrlKey: '[a-zA-Z0-9]{2,35}' }

# Simple routes

root:
    path: /
    defaults: { _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction, route: home, permanent: true }

home:
    path: /programmes
    defaults: { _controller: App\Controller\HomeController }

# Labs routes, for testing things

cloud_labs_root:
    path: /programmes/_cloudlabs
    defaults: { _controller: App\Controller\CloudLabsController, action: show }

cloud_labs:
    path: /programmes/_cloudlabs/{action}
    defaults: { _controller: App\Controller\CloudLabsController }

# Snippet player
snippet_get_records:
    path: /programmes/snippet/{recordsIds}.json
    defaults: { _controller: App\Controller\SnippetController }

# A to Z pages
atoz_index:
    path: /programmes/a-z
    defaults: { _controller: App\Controller\Atoz\IndexController }

atoz_redirect_current_list:
    path: /programmes/a-z/current
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: atoz_index, permanent: true }

atoz_naked_search:
    path: /programmes/a-z/by/{search}
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: atoz_show, slice: "player", permanent: true }
    requirements: { search: '^[a-zA-Z@]$' }

atoz_show:
    path: /programmes/a-z/by/{search}/{slice}
    defaults: { _controller: App\Controller\Atoz\ShowController }
    requirements: { slice: 'all|player', search: '^[a-zA-Z@]$' }

atoz_redirect_current_show:
    path: /programmes/a-z/by/{search}/current
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: atoz_show, slice: "player", permanent: true }
    requirements: { search: '^[a-zA-Z@]$' }

# Category pages
category_index:
    path: /programmes/{categoryType}
    defaults: { _controller: App\Controller\Category\IndexController }
    requirements: { categoryType: 'formats|genres' }

category_slice:
    path: /programmes/{categoryType}/{categoryHierarchy}/{slice}
    # Temporary until controller is implemented
    defaults: { _controller: App\Controller\Category\ListingController }
    requirements: { categoryType: 'formats|genres', categoryHierarchy: '.+', slice: 'player|all' }

category_metadata:
    path: /programmes/{categoryType}/{categoryHierarchy}
    defaults: { _controller: App\Controller\Category\MetadataController }
    requirements: { categoryType: 'formats|genres', categoryHierarchy: '.+' }

# Topic pages
programme_topics:
    path: /programmes/{pid}/topics
    defaults: { _controller: App\Controller\Topic\ListController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

programme_topic:
    path: /programmes/{pid}/topics/{topic}
    defaults: { _controller: App\Controller\Topic\ShowController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', topic: '.+?' }

topic_list:
    path: /programmes/topics
    defaults: { _controller: App\Controller\Topic\ListController }

topic_show:
    path: /programmes/topics/{topic}/{slice}
    defaults: { _controller: App\Controller\Topic\ShowController, slice: '' }
    requirements: { slice: 'video|audio', topic: '.+?' }

# Season sub page redirects
season_collection_members:
    path: /programmes/{pid}/members
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

season_members_all:
    path: /programmes/{pid}/members/all
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

season_schedules_by_date:
    path: /programmes/{pid}/schedules/{date}
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, permanent: true, ignoreAttributes: [date] }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/\d{2}/\d{2}' }

season_schedules:
    path: /programmes/{pid}/schedules
    controller: App\Controller\RedirectAndCacheController::redirectAction
    defaults: { route: find_by_pid, permanent: true }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
